showLandingPage:
  path: /
  controller: ControladorCliente::showLandingPage

login:
  path: /login
  controller: ControladorCliente::login

doLogin:
  path: /doLogin
  controller: ControladorCliente::doLogin

doLoginOAuth:
  path: /doLoginOAuth
  controller: ControladorCliente::doLoginOAuth

signup:
  path: /signup
  controller: ControladorCliente::signup

doSignup:
  path: /doSignup
  controller: ControladorCliente::doSignup

doSignupOAuth:
  path: /doSignup
  controller: ControladorCliente::doSignupOAuth

forgotPassword:
  path: /forgotPassword
  controller: ControladorCliente::forgotPassword

services:
  path: /services
  controller: ControladorCliente::services

bookService:
  path: /bookService
  controller: ControladorCliente::bookService

doBookService:
  path: /doBookService
  controller: ControladorTaller::doBookService

uploadMyVehicles:
  path: /uploadMyVehicles
  controller: ControladorCliente::cargarMisVehiculosAjax

serviceConfirmation:
  path: /serviceConfirmation
  controller: ControladorTaller::serviceConfirmation

aioParking:
  path: /aioParking
  controller: ControladorCliente::parking

aioParkingBookSimple:
  path: /aioParkingBookSimple
  controller: ControladorCliente::parkingSimple

aioParkingBookLongTerm:
  path: /aioParkingBookLongTerm
  controller: ControladorCliente::parkingLongTerm

bookParkingSimple:
  path: /bookParkingSimple
  controller: ControladorParking::bookParkingSimple

bookParkingLongTerm:
  path: /bookParkingLongTerm
  controller: ControladorCliente::bookParkingLongTerm

parkingConfirmation:
  path: /parkingConfirmation
  controller: ControladorParking::parkingConfirmation

products:
  path: /products
  controller: ControladorCliente::products

myAccount:
  path: /myAccount
  controller: ControladorCliente::myAccount

home:
  path: /home
  controller: ControladorCliente::home