-- 300 OTROS_PRODUCTOS
insert into otro_producto (id_producto, nombre) values (701, 'Aceite Mineral 1L');
insert into otro_producto (id_producto, nombre) values (702, 'Filtro de Aceite');
insert into otro_producto (id_producto, nombre) values (703, 'Bujías de Encendido');
insert into otro_producto (id_producto, nombre) values (704, 'Pastillas de Freno');
insert into otro_producto (id_producto, nombre) values (705, 'Discos de Freno');
insert into otro_producto (id_producto, nombre) values (706, 'Filtro de Aire');
insert into otro_producto (id_producto, nombre) values (707, 'Liquido de Frenos 500ml');
insert into otro_producto (id_producto, nombre) values (708, 'Radiador de Aluminio');
insert into otro_producto (id_producto, nombre) values (709, 'Termostato Motor');
insert into otro_producto (id_producto, nombre) values (710, 'Kit de Embrague');
insert into otro_producto (id_producto, nombre) values (711, 'Bombilla H7 12V');
insert into otro_producto (id_producto, nombre) values (712, 'Correa de Distribución');
insert into otro_producto (id_producto, nombre) values (713, 'Limpiaparabrisas 24p');
insert into otro_producto (id_producto, nombre) values (714, 'Aceite Sintético 5L');
insert into otro_producto (id_producto, nombre) values (715, 'Juego de Rótulas');
insert into otro_producto (id_producto, nombre) values (716, 'Filtro de Combustible');
insert into otro_producto (id_producto, nombre) values (717, 'Bomba de Agua');
insert into otro_producto (id_producto, nombre) values (718, 'Amortiguadores Delanteros');
insert into otro_producto (id_producto, nombre) values (719, 'Pastillas de Freno Traseras');
insert into otro_producto (id_producto, nombre) values (720, 'Sensor de Oxígeno');
insert into otro_producto (id_producto, nombre) values (721, 'Manguera de Radiador');
insert into otro_producto (id_producto, nombre) values (722, 'Cinturones de Seguridad');
insert into otro_producto (id_producto, nombre) values (723, 'Aceite de Transmisión');
insert into otro_producto (id_producto, nombre) values (724, 'Kit de Reparación Freno');
insert into otro_producto (id_producto, nombre) values (725, 'Juntas de Culata');
insert into otro_producto (id_producto, nombre) values (726, 'Filtro de Cabina');
insert into otro_producto (id_producto, nombre) values (727, 'Palanca de Cambios');
insert into otro_producto (id_producto, nombre) values (728, 'Juntas de Motor');
insert into otro_producto (id_producto, nombre) values (729, 'Batería de 12V');
insert into otro_producto (id_producto, nombre) values (730, 'Manguera de Combustible');
insert into otro_producto (id_producto, nombre) values (731, 'Aros de Pistón');
insert into otro_producto (id_producto, nombre) values (732, 'Tapones de Válvula');
insert into otro_producto (id_producto, nombre) values (733, 'Correa de Alternador');
insert into otro_producto (id_producto, nombre) values (734, 'Relé de Encendido');
insert into otro_producto (id_producto, nombre) values (735, 'Caja de Fusibles');
insert into otro_producto (id_producto, nombre) values (736, 'Acumulador de Energía');
insert into otro_producto (id_producto, nombre) values (737, 'Filtro de Aceite de Motor');
insert into otro_producto (id_producto, nombre) values (738, 'Ejes de Transmisión');
insert into otro_producto (id_producto, nombre) values (739, 'Aceite para Diferencial');
insert into otro_producto (id_producto, nombre) values (740, 'Aislador de Bujía');
insert into otro_producto (id_producto, nombre) values (741, 'Rodamientos de Rueda');
insert into otro_producto (id_producto, nombre) values (742, 'Kit de Fugas de Aceite');
insert into otro_producto (id_producto, nombre) values (743, 'Manguera de Climatización');
insert into otro_producto (id_producto, nombre) values (744, 'Repuestos de Suspensión');
insert into otro_producto (id_producto, nombre) values (745, 'Kit de Cadenas de Distribución');
insert into otro_producto (id_producto, nombre) values (746, 'Cilindro de Rueda');
insert into otro_producto (id_producto, nombre) values (747, 'Módulo de Encendido');
insert into otro_producto (id_producto, nombre) values (748, 'Manguera de Vacío');
insert into otro_producto (id_producto, nombre) values (749, 'Eje de Rotación');
insert into otro_producto (id_producto, nombre) values (750, 'Bobina de Encendido');
insert into otro_producto (id_producto, nombre) values (751, 'Filtro de Partículas');
insert into otro_producto (id_producto, nombre) values (752, 'Empaquetadura de Culata');
insert into otro_producto (id_producto, nombre) values (753, 'Dispositivo de Inyección');
insert into otro_producto (id_producto, nombre) values (754, 'Kit de Bujías');
insert into otro_producto (id_producto, nombre) values (755, 'Cables de Encendido');
insert into otro_producto (id_producto, nombre) values (756, 'Sensor de Temperatura');
insert into otro_producto (id_producto, nombre) values (757, 'Cilindro de Clutch');
insert into otro_producto (id_producto, nombre) values (758, 'Kit de Reparación de Fugas');
insert into otro_producto (id_producto, nombre) values (759, 'Rodillo de Distribución');
insert into otro_producto (id_producto, nombre) values (760, 'Bombas de Combustible');
insert into otro_producto (id_producto, nombre) values (761, 'Abrazaderas de Manguera');
insert into otro_producto (id_producto, nombre) values (762, 'Aceite de Motor 1L');
insert into otro_producto (id_producto, nombre) values (763, 'Manguera de Refrigeración');
insert into otro_producto (id_producto, nombre) values (764, 'Junta de Carter');
insert into otro_producto (id_producto, nombre) values (765, 'Alambre de Encendido');
insert into otro_producto (id_producto, nombre) values (766, 'Kit de Embrague Completo');
insert into otro_producto (id_producto, nombre) values (767, 'Estabilizador de Suspensión');
insert into otro_producto (id_producto, nombre) values (768, 'Filtro de Aire Acondicionado');
insert into otro_producto (id_producto, nombre) values (769, 'Aceite para Motor Diesel');
insert into otro_producto (id_producto, nombre) values (770, 'Amortiguadores Traseros');
insert into otro_producto (id_producto, nombre) values (771, 'Correa de Timing');
insert into otro_producto (id_producto, nombre) values (772, 'Sensor de Presión');
insert into otro_producto (id_producto, nombre) values (773, 'Pastillas de Freno Delanteras');
insert into otro_producto (id_producto, nombre) values (774, 'Bobina de Encendido 12V');
insert into otro_producto (id_producto, nombre) values (775, 'Reparación de Embrague');
insert into otro_producto (id_producto, nombre) values (776, 'Correa de Motor');
insert into otro_producto (id_producto, nombre) values (777, 'Filtro de Transmisión');
insert into otro_producto (id_producto, nombre) values (778, 'Aceite para Transmisión Automática');
insert into otro_producto (id_producto, nombre) values (779, 'Palanca de Ajuste');
insert into otro_producto (id_producto, nombre) values (780, 'Cilindro de Freno');
insert into otro_producto (id_producto, nombre) values (781, 'Juego de Arandelas');
insert into otro_producto (id_producto, nombre) values (782, 'Filtro de Aire Diesel');
insert into otro_producto (id_producto, nombre) values (783, 'Amortiguador de Suspensión');
insert into otro_producto (id_producto, nombre) values (784, 'Manguera de Escape');
insert into otro_producto (id_producto, nombre) values (785, 'Pastillas de Frenos de Cerámica');
insert into otro_producto (id_producto, nombre) values (786, 'Conjunto de Rodamientos');
insert into otro_producto (id_producto, nombre) values (787, 'Aceite de Caja de Cambios');
insert into otro_producto (id_producto, nombre) values (788, 'Kit de Reparación de Suspensión');
insert into otro_producto (id_producto, nombre) values (789, 'Tubo de Escapamiento');
insert into otro_producto (id_producto, nombre) values (790, 'Juntas de Empaque');
insert into otro_producto (id_producto, nombre) values (791, 'Filtro de Aceite de Transmisión');
insert into otro_producto (id_producto, nombre) values (792, 'Cinta de Aislamiento');
insert into otro_producto (id_producto, nombre) values (793, 'Eje de Motor');
insert into otro_producto (id_producto, nombre) values (794, 'Pastillas de Frenos de Alto Rendimiento');
insert into otro_producto (id_producto, nombre) values (795, 'Aceite de Transmisión Manual');
insert into otro_producto (id_producto, nombre) values (796, 'Filtro de Aire de Alto Flujo');
insert into otro_producto (id_producto, nombre) values (797, 'Manguera de Refrigerante');
insert into otro_producto (id_producto, nombre) values (798, 'Amortiguador Delantero Derecho');
insert into otro_producto (id_producto, nombre) values (799, 'Pastillas de Freno Cerámicas');
insert into otro_producto (id_producto, nombre) values (800, 'Aceite de Motor Sintético');
insert into otro_producto (id_producto, nombre) values (801, 'Rodamiento de Eje');
insert into otro_producto (id_producto, nombre) values (802, 'Kit de Embrague Hidráulico');
insert into otro_producto (id_producto, nombre) values (803, 'Filtro de Aceite para Motor Diesel');
insert into otro_producto (id_producto, nombre) values (804, 'Bombillas de Xenón');
insert into otro_producto (id_producto, nombre) values (805, 'Manguera de Climatización 30p');
insert into otro_producto (id_producto, nombre) values (806, 'Aceite para Caja de Cambios');
insert into otro_producto (id_producto, nombre) values (807, 'Kit de Reparación de Filtro');
insert into otro_producto (id_producto, nombre) values (808, 'Pastillas de Freno de Cerámica Delanteras');
insert into otro_producto (id_producto, nombre) values (809, 'Sensor de Nivel de Aceite');
insert into otro_producto (id_producto, nombre) values (810, 'Filtro de Aire de Motor');
insert into otro_producto (id_producto, nombre) values (811, 'Amortiguador Trasero Izquierdo');
insert into otro_producto (id_producto, nombre) values (812, 'Kit de Reparación de Radiador');
insert into otro_producto (id_producto, nombre) values (813, 'Aceite para Motor de Alto Rendimiento');
insert into otro_producto (id_producto, nombre) values (814, 'Manguera de Radiador Inferior');
insert into otro_producto (id_producto, nombre) values (815, 'Pastillas de Freno de Alto Rendimiento');
insert into otro_producto (id_producto, nombre) values (816, 'Filtro de Combustible Diesel');
insert into otro_producto (id_producto, nombre) values (817, 'Bombilla de Faro H7');
insert into otro_producto (id_producto, nombre) values (818, 'Kit de Reparación de Clutch');
insert into otro_producto (id_producto, nombre) values (819, 'Aceite de Motor de 5L');
insert into otro_producto (id_producto, nombre) values (820, 'Manguera de Refrigeración Inferior');
insert into otro_producto (id_producto, nombre) values (821, 'Pastillas de Frenos Traseras de Alto Rendimiento');
insert into otro_producto (id_producto, nombre) values (822, 'Filtro de Aire para Motor Diesel');
insert into otro_producto (id_producto, nombre) values (823, 'Aceite de Transmisión Automática 1L');
insert into otro_producto (id_producto, nombre) values (824, 'Kit de Repuestos de Embrague');
insert into otro_producto (id_producto, nombre) values (825, 'Rodamiento de Rueda Delantero');
insert into otro_producto (id_producto, nombre) values (826, 'Amortiguador Trasero Derecho');
insert into otro_producto (id_producto, nombre) values (827, 'Juntas de Motor de Alta Resistencia');
insert into otro_producto (id_producto, nombre) values (828, 'Manguera de Combustible 30p');
insert into otro_producto (id_producto, nombre) values (829, 'Sensor de Posición del Acelerador');
insert into otro_producto (id_producto, nombre) values (830, 'Aceite de Motor Mineral 1L');
insert into otro_producto (id_producto, nombre) values (831, 'Filtro de Aceite para Transmisión Manual');
insert into otro_producto (id_producto, nombre) values (832, 'Pastillas de Frenos de Cerámica Traseras');
insert into otro_producto (id_producto, nombre) values (833, 'Radiador de Aluminio para Motor');
insert into otro_producto (id_producto, nombre) values (834, 'Kit de Reparación de Motor');
insert into otro_producto (id_producto, nombre) values (835, 'Aceite para Transmisión Manual 1L');
insert into otro_producto (id_producto, nombre) values (836, 'Juntas de Empaque de Motor');
insert into otro_producto (id_producto, nombre) values (837, 'Manguera de Refrigeración Superior');
insert into otro_producto (id_producto, nombre) values (838, 'Pastillas de Freno Traseras de Alto Rendimiento');
insert into otro_producto (id_producto, nombre) values (839, 'Bombilla de Faro H4');
insert into otro_producto (id_producto, nombre) values (840, 'Kit de Reparación de Bombilla');
insert into otro_producto (id_producto, nombre) values (841, 'Sensor de Temperatura del Motor');
insert into otro_producto (id_producto, nombre) values (842, 'Aceite de Motor Diesel 1L');
insert into otro_producto (id_producto, nombre) values (843, 'Rodamiento de Eje Trasero');
insert into otro_producto (id_producto, nombre) values (844, 'Amortiguador Delantero Izquierdo');
insert into otro_producto (id_producto, nombre) values (845, 'Filtro de Aire para Motor Gasolina');
insert into otro_producto (id_producto, nombre) values (846, 'Juntas de Motor para Alta Temperatura');
insert into otro_producto (id_producto, nombre) values (847, 'Kit de Reparación de Suspensión Delantera');
insert into otro_producto (id_producto, nombre) values (848, 'Manguera de Radiador Superior');
insert into otro_producto (id_producto, nombre) values (849, 'Pastillas de Freno de Cerámica Traseras');
insert into otro_producto (id_producto, nombre) values (850, 'Aceite de Motor para Alto Rendimiento');
insert into otro_producto (id_producto, nombre) values (851, 'Bombilla de Faro H1');
insert into otro_producto (id_producto, nombre) values (852, 'Kit de Reparación de Fugas de Aceite');
insert into otro_producto (id_producto, nombre) values (853, 'Sensor de Presión de Aceite');
insert into otro_producto (id_producto, nombre) values (854, 'Manguera de Radiador Inferior');
insert into otro_producto (id_producto, nombre) values (855, 'Pastillas de Freno Delanteras de Alto Rendimiento');
insert into otro_producto (id_producto, nombre) values (856, 'Aceite de Transmisión Manual 5L');
insert into otro_producto (id_producto, nombre) values (857, 'Filtro de Aire de Motor Gasolina');
insert into otro_producto (id_producto, nombre) values (858, 'Rodamiento de Eje Delantero');
insert into otro_producto (id_producto, nombre) values (859, 'Amortiguador Trasero Central');
insert into otro_producto (id_producto, nombre) values (860, 'Juntas de Empaque de Alta Resistencia');
insert into otro_producto (id_producto, nombre) values (861, 'Kit de Reparación de Eje');
insert into otro_producto (id_producto, nombre) values (862, 'Manguera de Refrigerante Inferior');
insert into otro_producto (id_producto, nombre) values (863, 'Aceite para Caja de Cambios Manual');
insert into otro_producto (id_producto, nombre) values (864, 'Filtro de Aceite de Motor Diesel');
insert into otro_producto (id_producto, nombre) values (865, 'Pastillas de Frenos de Alto Rendimiento Traseras');
insert into otro_producto (id_producto, nombre) values (866, 'Bombilla de Faro H9');
insert into otro_producto (id_producto, nombre) values (867, 'Kit de Reparación de Radiador Inferior');
insert into otro_producto (id_producto, nombre) values (868, 'Sensor de Nivel de Combustible');
insert into otro_producto (id_producto, nombre) values (869, 'Aceite de Motor de 1L Sintético');
insert into otro_producto (id_producto, nombre) values (870, 'Manguera de Escape de Alto Rendimiento');
insert into otro_producto (id_producto, nombre) values (871, 'Pastillas de Frenos de Cerámica Delanteras');
insert into otro_producto (id_producto, nombre) values (872, 'Radiador de Refrigeración');
insert into otro_producto (id_producto, nombre) values (873, 'Juntas de Culata de Alta Resistencia');
insert into otro_producto (id_producto, nombre) values (874, 'Amortiguador Delantero Central');
insert into otro_producto (id_producto, nombre) values (875, 'Filtro de Aire Diesel para Motor');
insert into otro_producto (id_producto, nombre) values (876, 'Kit de Reparación de Embrague Hidráulico');
insert into otro_producto (id_producto, nombre) values (877, 'Aceite de Transmisión Automática 5L');
insert into otro_producto (id_producto, nombre) values (878, 'Manguera de Climatización de Alto Rendimiento');
insert into otro_producto (id_producto, nombre) values (879, 'Bombilla de Faro H11');
insert into otro_producto (id_producto, nombre) values (880, 'Sensor de Temperatura del Combustible');
insert into otro_producto (id_producto, nombre) values (881, 'Pastillas de Freno Cerámicas Delanteras');
insert into otro_producto (id_producto, nombre) values (882, 'Aceite Mineral 5L');
insert into otro_producto (id_producto, nombre) values (883, 'Juntas de Motor para Alta Temperatura');
insert into otro_producto (id_producto, nombre) values (884, 'Manguera de Radiador Lateral');
insert into otro_producto (id_producto, nombre) values (885, 'Filtro de Combustible de Alto Rendimiento');
insert into otro_producto (id_producto, nombre) values (886, 'Amortiguador Trasero Central Derecho');
insert into otro_producto (id_producto, nombre) values (887, 'Kit de Reparación de Eje Trasero');
insert into otro_producto (id_producto, nombre) values (888, 'Aceite para Motor Gasolina 1L');
insert into otro_producto (id_producto, nombre) values (889, 'Filtro de Aire para Motor Diesel');
insert into otro_producto (id_producto, nombre) values (890, 'Pastillas de Freno de Cerámica Traseras de Alto Rendimiento');
insert into otro_producto (id_producto, nombre) values (891, 'Bombilla de Faro H8');
insert into otro_producto (id_producto, nombre) values (892, 'Kit de Reparación de Transmisión Manual');
insert into otro_producto (id_producto, nombre) values (893, 'Sensor de Posición del Motor');
insert into otro_producto (id_producto, nombre) values (894, 'Aceite para Caja de Cambios Diesel');
insert into otro_producto (id_producto, nombre) values (895, 'Manguera de Climatización Inferior');
insert into otro_producto (id_producto, nombre) values (896, 'Pastillas de Frenos Cerámicas Traseras');
insert into otro_producto (id_producto, nombre) values (897, 'Aceite Mineral 1L');
insert into otro_producto (id_producto, nombre) values (898, 'Filtro de Aceite');
insert into otro_producto (id_producto, nombre) values (899, 'Bujías de Encendido');
insert into otro_producto (id_producto, nombre) values (900, 'Pastillas de Freno');
insert into otro_producto (id_producto, nombre) values (901, 'Discos de Freno');
insert into otro_producto (id_producto, nombre) values (902, 'Filtro de Aire');
insert into otro_producto (id_producto, nombre) values (903, 'Liquido de Frenos 500ml');
insert into otro_producto (id_producto, nombre) values (904, 'Radiador de Aluminio');
insert into otro_producto (id_producto, nombre) values (905, 'Termostato Motor');
insert into otro_producto (id_producto, nombre) values (906, 'Kit de Embrague');
insert into otro_producto (id_producto, nombre) values (907, 'Bombilla H7 12V');
insert into otro_producto (id_producto, nombre) values (908, 'Correa de Distribución');
insert into otro_producto (id_producto, nombre) values (909, 'Limpiaparabrisas 24p');
insert into otro_producto (id_producto, nombre) values (910, 'Aceite Sintético 5L');
insert into otro_producto (id_producto, nombre) values (911, 'Juego de Rótulas');
insert into otro_producto (id_producto, nombre) values (912, 'Filtro de Combustible');
insert into otro_producto (id_producto, nombre) values (913, 'Bomba de Agua');
insert into otro_producto (id_producto, nombre) values (914, 'Amortiguadores Delanteros');
insert into otro_producto (id_producto, nombre) values (915, 'Pastillas de Freno Traseras');
insert into otro_producto (id_producto, nombre) values (916, 'Sensor de Oxígeno');
insert into otro_producto (id_producto, nombre) values (917, 'Manguera de Radiador');
insert into otro_producto (id_producto, nombre) values (918, 'Cinturones de Seguridad');
insert into otro_producto (id_producto, nombre) values (919, 'Aceite de Transmisión');
insert into otro_producto (id_producto, nombre) values (920, 'Kit de Reparación Freno');
insert into otro_producto (id_producto, nombre) values (921, 'Juntas de Culata');
insert into otro_producto (id_producto, nombre) values (922, 'Filtro de Cabina');
insert into otro_producto (id_producto, nombre) values (923, 'Palanca de Cambios');
insert into otro_producto (id_producto, nombre) values (924, 'Juntas de Motor');
insert into otro_producto (id_producto, nombre) values (925, 'Batería de 12V');
insert into otro_producto (id_producto, nombre) values (926, 'Manguera de Combustible');
insert into otro_producto (id_producto, nombre) values (927, 'Aros de Pistón');
insert into otro_producto (id_producto, nombre) values (928, 'Tapones de Válvula');
insert into otro_producto (id_producto, nombre) values (929, 'Correa de Alternador');
insert into otro_producto (id_producto, nombre) values (930, 'Relé de Encendido');
insert into otro_producto (id_producto, nombre) values (931, 'Caja de Fusibles');
insert into otro_producto (id_producto, nombre) values (932, 'Acumulador de Energía');
insert into otro_producto (id_producto, nombre) values (933, 'Filtro de Aceite de Motor');
insert into otro_producto (id_producto, nombre) values (934, 'Ejes de Transmisión');
insert into otro_producto (id_producto, nombre) values (935, 'Aceite para Diferencial');
insert into otro_producto (id_producto, nombre) values (936, 'Aislador de Bujía');
insert into otro_producto (id_producto, nombre) values (937, 'Rodamientos de Rueda');
insert into otro_producto (id_producto, nombre) values (938, 'Kit de Fugas de Aceite');
insert into otro_producto (id_producto, nombre) values (939, 'Manguera de Climatización');
insert into otro_producto (id_producto, nombre) values (940, 'Repuestos de Suspensión');
insert into otro_producto (id_producto, nombre) values (941, 'Kit de Cadenas de Distribución');
insert into otro_producto (id_producto, nombre) values (942, 'Cilindro de Rueda');
insert into otro_producto (id_producto, nombre) values (943, 'Módulo de Encendido');
insert into otro_producto (id_producto, nombre) values (944, 'Manguera de Vacío');
insert into otro_producto (id_producto, nombre) values (945, 'Eje de Rotación');
insert into otro_producto (id_producto, nombre) values (946, 'Bobina de Encendido');
insert into otro_producto (id_producto, nombre) values (947, 'Filtro de Partículas');
insert into otro_producto (id_producto, nombre) values (948, 'Empaquetadura de Culata');
insert into otro_producto (id_producto, nombre) values (949, 'Dispositivo de Inyección');
insert into otro_producto (id_producto, nombre) values (950, 'Kit de Bujías');
insert into otro_producto (id_producto, nombre) values (951, 'Cables de Encendido');
insert into otro_producto (id_producto, nombre) values (952, 'Sensor de Temperatura');
insert into otro_producto (id_producto, nombre) values (953, 'Cilindro de Clutch');
insert into otro_producto (id_producto, nombre) values (954, 'Kit de Reparación de Fugas');
insert into otro_producto (id_producto, nombre) values (955, 'Rodillo de Distribución');
insert into otro_producto (id_producto, nombre) values (956, 'Bombas de Combustible');
insert into otro_producto (id_producto, nombre) values (957, 'Abrazaderas de Manguera');
insert into otro_producto (id_producto, nombre) values (958, 'Aceite de Motor 1L');
insert into otro_producto (id_producto, nombre) values (959, 'Manguera de Refrigeración');
insert into otro_producto (id_producto, nombre) values (960, 'Junta de Carter');
insert into otro_producto (id_producto, nombre) values (961, 'Alambre de Encendido');
insert into otro_producto (id_producto, nombre) values (962, 'Kit de Embrague Completo');
insert into otro_producto (id_producto, nombre) values (963, 'Estabilizador de Suspensión');
insert into otro_producto (id_producto, nombre) values (964, 'Filtro de Aire Acondicionado');
insert into otro_producto (id_producto, nombre) values (965, 'Aceite para Motor Diesel');
insert into otro_producto (id_producto, nombre) values (966, 'Amortiguadores Traseros');
insert into otro_producto (id_producto, nombre) values (967, 'Correa de Timing');
insert into otro_producto (id_producto, nombre) values (968, 'Sensor de Presión');
insert into otro_producto (id_producto, nombre) values (969, 'Pastillas de Freno Delanteras');
insert into otro_producto (id_producto, nombre) values (970, 'Bobina de Encendido 12V');
insert into otro_producto (id_producto, nombre) values (971, 'Reparación de Embrague');
insert into otro_producto (id_producto, nombre) values (972, 'Correa de Motor');
insert into otro_producto (id_producto, nombre) values (973, 'Filtro de Transmisión');
insert into otro_producto (id_producto, nombre) values (974, 'Aceite para Transmisión Automática');
insert into otro_producto (id_producto, nombre) values (975, 'Palanca de Ajuste');
insert into otro_producto (id_producto, nombre) values (976, 'Cilindro de Freno');
insert into otro_producto (id_producto, nombre) values (977, 'Juego de Arandelas');
insert into otro_producto (id_producto, nombre) values (978, 'Filtro de Aire Diesel');
insert into otro_producto (id_producto, nombre) values (979, 'Amortiguador de Suspensión');
insert into otro_producto (id_producto, nombre) values (980, 'Manguera de Escape');
insert into otro_producto (id_producto, nombre) values (981, 'Pastillas de Frenos de Cerámica');
insert into otro_producto (id_producto, nombre) values (982, 'Conjunto de Rodamientos');
insert into otro_producto (id_producto, nombre) values (983, 'Aceite de Caja de Cambios');
insert into otro_producto (id_producto, nombre) values (984, 'Kit de Reparación de Suspensión');
insert into otro_producto (id_producto, nombre) values (985, 'Tubo de Escapamiento');
insert into otro_producto (id_producto, nombre) values (986, 'Juntas de Empaque');
insert into otro_producto (id_producto, nombre) values (987, 'Filtro de Aceite de Transmisión');
insert into otro_producto (id_producto, nombre) values (988, 'Cinta de Aislamiento');
insert into otro_producto (id_producto, nombre) values (989, 'Eje de Motor');
insert into otro_producto (id_producto, nombre) values (990, 'Pastillas de Frenos de Alto Rendimiento');
insert into otro_producto (id_producto, nombre) values (991, 'Aceite de Transmisión Manual');
insert into otro_producto (id_producto, nombre) values (992, 'Filtro de Aire de Alto Flujo');
insert into otro_producto (id_producto, nombre) values (993, 'Manguera de Refrigerante');
insert into otro_producto (id_producto, nombre) values (994, 'Amortiguador Delantero Derecho');
insert into otro_producto (id_producto, nombre) values (995, 'Pastillas de Freno Cerámicas');
insert into otro_producto (id_producto, nombre) values (996, 'Aceite de Motor Sintético');
insert into otro_producto (id_producto, nombre) values (997, 'Rodamiento de Eje');
insert into otro_producto (id_producto, nombre) values (998, 'Kit de Embrague Hidráulico');
insert into otro_producto (id_producto, nombre) values (999, 'Filtro de Aceite para Motor Diesel');
insert into otro_producto (id_producto, nombre) values (1000, 'Bombillas de Xenón');