-- 100 VEHICULOS
insert into vehiculo (matricula, marca, modelo, tipo, color) values ('5HUU2O19', 'Chevrolet', 'Cavalier', 'utilitario', 'd61cd4');
insert into vehiculo (matricula, marca, modelo, tipo, color) values ('L3531J2I', 'Nissan', 'Xterra', 'moto', '14137f');
insert into vehiculo (matricula, marca, modelo, tipo, color) values ('18S0W7AJ', 'Audi', 'A4', 'moto', 'dc0d30');
insert into vehiculo (matricula, marca, modelo, tipo, color) values ('XT7638U1', 'Volvo', 'XC90', 'camioneta', 'c0a3ec');
insert into vehiculo (matricula, marca, modelo, tipo, color) values ('B9Q2TB9A', 'Dodge', 'Neon', 'auto', 'd955ba');
insert into vehiculo (matricula, marca, modelo, tipo, color) values ('9LN5700I', 'Land Rover', 'Defender 90', 'auto', '836ed5');
insert into vehiculo (matricula, marca, modelo, tipo, color) values ('DV1O9Z8S', 'Ford', 'Aerostar', 'utilitario', '7c0d40');
insert into vehiculo (matricula, marca, modelo, tipo, color) values ('5N4V5MWL', 'Porsche', '911', 'auto', '68c89f');
insert into vehiculo (matricula, marca, modelo, tipo, color) values ('W4RG8J6K', 'BMW', '5 Series', 'camioneta', '1fe0da');
insert into vehiculo (matricula, marca, modelo, tipo, color) values ('XWJSNN4X', 'Pontiac', 'Montana', 'camioneta', 'f6d27e');
insert into vehiculo (matricula, marca, modelo, tipo, color) values ('X1J7KD3W', 'Ford', 'E250', 'camión', 'c79130');
insert into vehiculo (matricula, marca, modelo, tipo, color) values ('3E414R49', 'Ford', 'Fiesta', 'utilitario', '08f2eb');
insert into vehiculo (matricula, marca, modelo, tipo, color) values ('OL419RY2', 'Chevrolet', 'Corvette', 'moto', '9ecb28');
insert into vehiculo (matricula, marca, modelo, tipo, color) values ('Y1Z73KND', 'Dodge', 'Dakota Club', 'camioneta', '311bed');
insert into vehiculo (matricula, marca, modelo, tipo, color) values ('R62XVGE8', 'Chevrolet', 'Colorado', 'camión', '9e69cd');
insert into vehiculo (matricula, marca, modelo, tipo, color) values ('G5GYF50J', 'Mercury', 'Tracer', 'auto', '73193a');
insert into vehiculo (matricula, marca, modelo, tipo, color) values ('VACK8JZ4', 'BMW', '1 Series', 'camioneta', '49e886');
insert into vehiculo (matricula, marca, modelo, tipo, color) values ('157I0186', 'Mazda', 'B-Series', 'moto', '178573');
insert into vehiculo (matricula, marca, modelo, tipo, color) values ('EWC39L26', 'Plymouth', 'Breeze', 'utilitario', 'd949d5');
insert into vehiculo (matricula, marca, modelo, tipo, color) values ('J6OPN0P8', 'Audi', 'A4', 'auto', '81aca3');
insert into vehiculo (matricula, marca, modelo, tipo, color) values ('5Z69512Y', 'Mitsubishi', 'GTO', 'auto', '1ebd57');
insert into vehiculo (matricula, marca, modelo, tipo, color) values ('H0619363', 'Audi', 'riolet', 'moto', 'aba29c');
insert into vehiculo (matricula, marca, modelo, tipo, color) values ('3MQG3OM8', 'Infiniti', 'G37', 'moto', 'b6271c');
insert into vehiculo (matricula, marca, modelo, tipo, color) values ('VG72WA46', 'Saab', '900', 'utilitario', 'a7e4f1');
insert into vehiculo (matricula, marca, modelo, tipo, color) values ('24Y5TNK7', 'Chrysler', 'Cirrus', 'moto', 'd62e1b');
insert into vehiculo (matricula, marca, modelo, tipo, color) values ('78T8K58A', 'Cadillac', 'Escalade', 'moto', '97153b');
insert into vehiculo (matricula, marca, modelo, tipo, color) values ('AXO13HJS', 'Pontiac', 'Bonneville', 'utilitario', '9fe4d3');
insert into vehiculo (matricula, marca, modelo, tipo, color) values ('3L9RJ0T4', 'Mazda', 'MX-3', 'utilitario', '5d4ec4');
insert into vehiculo (matricula, marca, modelo, tipo, color) values ('0SPHX7AX', 'Dodge', 'Shadow', 'utilitario', 'e62d3f');
insert into vehiculo (matricula, marca, modelo, tipo, color) values ('Q100S7TG', 'GMC', 'Savana 1500', 'auto', 'a6ffd0');
insert into vehiculo (matricula, marca, modelo, tipo, color) values ('O1196GNB', 'Chevrolet', 'Camaro', 'utilitario', '43878d');
insert into vehiculo (matricula, marca, modelo, tipo, color) values ('J193XN62', 'Volkswagen', 'Fox', 'auto', '12a830');
insert into vehiculo (matricula, marca, modelo, tipo, color) values ('7DV7SW18', 'Honda', 'Prelude', 'camioneta', '26ee24');
insert into vehiculo (matricula, marca, modelo, tipo, color) values ('4PWJ420P', 'Ford', 'F350', 'utilitario', '720828');
insert into vehiculo (matricula, marca, modelo, tipo, color) values ('KIZSX93Y', 'Subaru', 'Leone', 'camioneta', '07dc2f');
insert into vehiculo (matricula, marca, modelo, tipo, color) values ('I9TQ6948', 'Mercedes-Benz', 'E-Class', 'camioneta', '79352e');
insert into vehiculo (matricula, marca, modelo, tipo, color) values ('9YY85999', 'Dodge', 'Ram 3500', 'auto', '97520d');
insert into vehiculo (matricula, marca, modelo, tipo, color) values ('IW754FT2', 'Land Rover', 'Range Rover', 'camioneta', '7b4c66');
insert into vehiculo (matricula, marca, modelo, tipo, color) values ('4Y1W15GU', 'Lexus', 'SC', 'camioneta', '45a446');
insert into vehiculo (matricula, marca, modelo, tipo, color) values ('04PQX59F', 'Cadillac', 'Seville', 'camioneta', 'bd88bf');
insert into vehiculo (matricula, marca, modelo, tipo, color) values ('65J8414E', 'Honda', 'Accord Crosstour', 'camión', '299d50');
insert into vehiculo (matricula, marca, modelo, tipo, color) values ('91L3NOJ4', 'Pontiac', 'Grand Am', 'moto', '437aa6');
insert into vehiculo (matricula, marca, modelo, tipo, color) values ('IPBY2BJV', 'Honda', 'CR-V', 'camión', 'c7b771');
insert into vehiculo (matricula, marca, modelo, tipo, color) values ('9060E7S7', 'Volkswagen', 'GTI', 'moto', 'adf5b8');
insert into vehiculo (matricula, marca, modelo, tipo, color) values ('SF006O8A', 'Infiniti', 'QX', 'utilitario', '899198');
insert into vehiculo (matricula, marca, modelo, tipo, color) values ('I343H6L4', 'Porsche', 'Boxster', 'camioneta', '88a2c2');
insert into vehiculo (matricula, marca, modelo, tipo, color) values ('J8Y5O73B', 'Toyota', 'Tacoma Xtra', 'camión', '6d7abd');
insert into vehiculo (matricula, marca, modelo, tipo, color) values ('8KDWRB20', 'Lincoln', 'Navigator', 'camioneta', 'ee5e3c');
insert into vehiculo (matricula, marca, modelo, tipo, color) values ('LLV5LG20', 'Pontiac', 'LeMans', 'utilitario', 'eb4730');
insert into vehiculo (matricula, marca, modelo, tipo, color) values ('60FVDY8B', 'Lotus', 'Exige', 'auto', '8b02ab');
insert into vehiculo (matricula, marca, modelo, tipo, color) values ('42T7S1C6', 'Fiat', 'Nuova 500', 'utilitario', '4a3eac');
insert into vehiculo (matricula, marca, modelo, tipo, color) values ('6QY3T560', 'GMC', 'Yukon XL 2500', 'moto', '916526');
insert into vehiculo (matricula, marca, modelo, tipo, color) values ('Z33MR03J', 'Ford', 'F250', 'moto', '07e266');
insert into vehiculo (matricula, marca, modelo, tipo, color) values ('Z9V16698', 'Chrysler', 'PT Cruiser', 'utilitario', 'dd4198');
insert into vehiculo (matricula, marca, modelo, tipo, color) values ('5J6F053F', 'Ford', 'E150', 'camioneta', '4d3f72');
insert into vehiculo (matricula, marca, modelo, tipo, color) values ('JV318UM3', 'Pontiac', 'Sunfire', 'camión', 'cfb1fe');
insert into vehiculo (matricula, marca, modelo, tipo, color) values ('V4Y7I3R2', 'Volkswagen', 'CC', 'moto', '9ca252');
insert into vehiculo (matricula, marca, modelo, tipo, color) values ('105L946O', 'Hyundai', 'Tiburon', 'moto', '639872');
insert into vehiculo (matricula, marca, modelo, tipo, color) values ('ED1MMJ8Q', 'Lincoln', 'Continental', 'moto', 'c6c173');
insert into vehiculo (matricula, marca, modelo, tipo, color) values ('U0JY229V', 'Kia', 'Sedona', 'camión', 'd937a6');
insert into vehiculo (matricula, marca, modelo, tipo, color) values ('9UGHHYZ9', 'Ford', 'Explorer', 'camioneta', '586c61');
insert into vehiculo (matricula, marca, modelo, tipo, color) values ('ME548P43', 'Ford', 'Expedition', 'moto', '6547ae');
insert into vehiculo (matricula, marca, modelo, tipo, color) values ('Z9493Q13', 'Honda', 'Accord', 'moto', 'd2ffd8');
insert into vehiculo (matricula, marca, modelo, tipo, color) values ('T9464VXB', 'Volvo', 'C70', 'moto', '83c544');
insert into vehiculo (matricula, marca, modelo, tipo, color) values ('UK5U994T', 'Cadillac', 'Escalade', 'utilitario', '315c06');
insert into vehiculo (matricula, marca, modelo, tipo, color) values ('895Y5H7O', 'Volkswagen', 'Jetta', 'utilitario', '45a79f');
insert into vehiculo (matricula, marca, modelo, tipo, color) values ('Z001OCJ1', 'Dodge', 'Ram 1500 Club', 'camioneta', '350039');
insert into vehiculo (matricula, marca, modelo, tipo, color) values ('0FG2K1NH', 'Audi', '100', 'utilitario', 'bab79f');
insert into vehiculo (matricula, marca, modelo, tipo, color) values ('2Q65QR14', 'Toyota', 'FJ Cruiser', 'utilitario', 'fd2e76');
insert into vehiculo (matricula, marca, modelo, tipo, color) values ('D99KJT5F', 'GMC', 'Sierra 1500', 'utilitario', '5c54cb');
insert into vehiculo (matricula, marca, modelo, tipo, color) values ('90UQX480', 'Toyota', 'Prius', 'camioneta', '403356');
insert into vehiculo (matricula, marca, modelo, tipo, color) values ('632SL0GJ', 'Ford', 'F250', 'utilitario', '9c6294');
insert into vehiculo (matricula, marca, modelo, tipo, color) values ('027WO40K', 'Pontiac', 'Grand Am', 'camión', '11a9a5');
insert into vehiculo (matricula, marca, modelo, tipo, color) values ('K027W1AE', 'Chevrolet', 'Express', 'camioneta', '9a4a9a');
insert into vehiculo (matricula, marca, modelo, tipo, color) values ('P1V12362', 'Hyundai', 'Santa Fe', 'camión', '060586');
insert into vehiculo (matricula, marca, modelo, tipo, color) values ('75J97R32', 'Lexus', 'ES', 'camión', '1624ef');
insert into vehiculo (matricula, marca, modelo, tipo, color) values ('XIJA8RC2', 'GMC', '3500 Club Coupe', 'utilitario', 'f2219b');
insert into vehiculo (matricula, marca, modelo, tipo, color) values ('85K64LU5', 'Lincoln', 'Mark VIII', 'utilitario', 'd36a61');
insert into vehiculo (matricula, marca, modelo, tipo, color) values ('G205EH8Y', 'Mazda', '626', 'camioneta', '474b91');
insert into vehiculo (matricula, marca, modelo, tipo, color) values ('5H37G7Q9', 'Mazda', 'Mazdaspeed 3', 'camión', '623b50');
insert into vehiculo (matricula, marca, modelo, tipo, color) values ('X0QRYN8U', 'Ford', 'Probe', 'moto', '5081cc');
insert into vehiculo (matricula, marca, modelo, tipo, color) values ('9HS2401Z', 'GMC', 'Sierra 2500', 'moto', 'c0a073');
insert into vehiculo (matricula, marca, modelo, tipo, color) values ('15BT9N72', 'Ford', 'Explorer', 'moto', '3943bb');
insert into vehiculo (matricula, marca, modelo, tipo, color) values ('B514137Q', 'Kia', 'Sorento', 'camioneta', '7935e8');
insert into vehiculo (matricula, marca, modelo, tipo, color) values ('C0L6N64V', 'Buick', 'LeSabre', 'moto', 'b94040');
insert into vehiculo (matricula, marca, modelo, tipo, color) values ('3H5TEV54', 'Aptera', 'Typ-1', 'moto', '01d399');
insert into vehiculo (matricula, marca, modelo, tipo, color) values ('NJ3177HS', 'Toyota', '4Runner', 'moto', '8ad195');
insert into vehiculo (matricula, marca, modelo, tipo, color) values ('W81GRJZQ', 'Toyota', 'Avalon', 'auto', '8fcffd');
insert into vehiculo (matricula, marca, modelo, tipo, color) values ('J8DHIXVA', 'Volvo', '850', 'auto', 'c86cd8');
insert into vehiculo (matricula, marca, modelo, tipo, color) values ('645W9666', 'Mercedes-Benz', 'SLK-Class', 'camioneta', '7c5ac0');
insert into vehiculo (matricula, marca, modelo, tipo, color) values ('CG108BUD', 'Ford', 'F350', 'auto', '8f26cc');
insert into vehiculo (matricula, marca, modelo, tipo, color) values ('9GT9X983', 'Jeep', 'Wrangler', 'auto', 'f47313');
insert into vehiculo (matricula, marca, modelo, tipo, color) values ('I5X3P3T2', 'Ford', 'Torino', 'auto', 'f82ef6');
insert into vehiculo (matricula, marca, modelo, tipo, color) values ('3H64B633', 'Lincoln', 'Navigator', 'moto', 'edba26');
insert into vehiculo (matricula, marca, modelo, tipo, color) values ('48TQ8C64', 'Chevrolet', 'K5 Blazer', 'utilitario', '1f4b8e');
insert into vehiculo (matricula, marca, modelo, tipo, color) values ('90S6633B', 'Acura', 'Integra', 'utilitario', 'b22943');
insert into vehiculo (matricula, marca, modelo, tipo, color) values ('7VSDRTPH', 'Lexus', 'LX', 'camioneta', '5c4037');
insert into vehiculo (matricula, marca, modelo, tipo, color) values ('VU894959', 'Lexus', 'LS', 'utilitario', 'ecbc2d');
insert into vehiculo (matricula, marca, modelo, tipo, color) values ('A63HP7S5', 'Jeep', 'Cherokee', 'moto', '2633f5');
insert into vehiculo (matricula, marca, modelo, tipo, color) values ('IW2YHLOJ', 'Hummer', 'H1', 'utilitario', '885449');