showLandingPage:
  path: /
  controller: ControladorCliente::showLandingPage
  methods: GET

login:
  path: /login
  controller: ControladorCliente::login
  methods: GET

doLogin:
  path: /doLogin
  controller: ControladorCliente::doLogin
  methods: POST

doLoginOAuth:
  path: /doLoginOAuth
  controller: ControladorCliente::doLoginOAuth
  methods: GET

signup:
  path: /signup
  controller: ControladorCliente::signup
  methods: GET

doSignup:
  path: /doSignup
  controller: ControladorCliente::doSignup
  methods: POST

doSignupOAuth:
  path: /doSignup
  controller: ControladorCliente::doSignupOAuth
  methods: POST

forgotPassword:
  path: /forgotPassword
  controller: ControladorCliente::forgotPassword
  methods: GET

services:
  path: /services
  controller: ControladorCliente::services
  methods: GET

bookService:
  path: /bookService
  controller: ControladorCliente::bookService
  methods: GET

doBookService:
  path: /doBookService
  controller: ControladorTaller::doBookService
  methods: POST

uploadMyVehicles:
  path: /uploadMyVehicles
  controller: ControladorCliente::cargarMisVehiculosAjax

serviceConfirmation:
  path: /serviceConfirmation
  controller: ControladorTaller::serviceConfirmation
  methods: GET

aioParking:
  path: /aioParking
  controller: ControladorCliente::parking
  methods: GET

aioParkingBookSimple:
  path: /aioParkingBookSimple
  controller: ControladorCliente::parkingSimple
  methods: GET

aioParkingBookLongTerm:
  path: /aioParkingBookLongTerm
  controller: ControladorCliente::parkingLongTerm
  methods: GET

bookParkingSimple:
  path: /bookParkingSimple
  controller: ControladorParking::bookParkingSimple
  methods: POST

bookParkingLongTerm:
  path: /bookParkingLongTerm
  controller: ControladorCliente::bookParkingLongTerm
  methods: POST

parkingConfirmation:
  path: /parkingConfirmation
  controller: ControladorParking::parkingConfirmation
  methods: GET

products:
  path: /products
  controller: ControladorCliente::products
  methods: GET

myAccount:
  path: /myAccount
  controller: ControladorCliente::myAccount
  methods: GET

home:
  path: /home
  controller: ControladorCliente::home
  methods: GET