showLandingPage:
  path: /
  controller: Sigae\Controllers\ControladorCliente::showLandingPage
  methods: GET

# Rutas de cliente
# Home y preguntas frecuentes
home:
  path: /home
  controller: Sigae\Controllers\ControladorCliente::home
  methods: GET

faq:
  path: /faq
  controller: Sigae\Controllers\ControladorCliente::faq
  methods: GET

# Gestion de cuenta
login:
  path: /login
  controller: Sigae\Controllers\ControladorCliente::login
  methods: GET

logout:
  path: /logout
  controller: Sigae\Controllers\ControladorCliente::logout
  methods: GET

doLogin:
  path: /doLogin
  controller: Sigae\Controllers\ControladorCliente::doLogin
  methods: POST

doLoginOAuth:
  path: /doLoginOAuth
  controller: Sigae\Controllers\ControladorCliente::doLoginOAuth
  methods: GET

signup:
  path: /signup
  controller: Sigae\Controllers\ControladorCliente::signup
  methods: GET

doSignup:
  path: /doSignup
  controller: Sigae\Controllers\ControladorCliente::doSignup
  methods: POST

forgotPassword:
  path: /forgotPassword
  controller: Sigae\Controllers\ControladorCliente::forgotPassword
  methods: GET

myAccount:
  path: /myAccount
  controller: Sigae\Controllers\ControladorCliente::myAccount
  methods: GET

editMyAccount:
  path: /editMyAccount
  controller: Sigae\Controllers\ControladorCliente::editMyAccount
  methods: POST

# Gestion de servicios de taller y parking
# Mis servicios
myBookedServices:
  path: /myServices
  controller: Sigae\Controllers\ControladorCliente::myBookedServices
  methods: GET

cancelService:
  path: /cancelService
  controller: Sigae\Controllers\ControladorCliente::cancelService
  methods: POST

# Servicios de taller
services:
  path: /services
  controller: Sigae\Controllers\ControladorCliente::services
  methods: GET

bookService:
  path: /bookService
  controller: Sigae\Controllers\ControladorTaller::bookService
  methods: GET

doBookService:
  path: /doBookService
  controller: Sigae\Controllers\ControladorTaller::doBookService
  methods: POST

serviceConfirmation:
  path: /serviceConfirmation
  controller: Sigae\Controllers\ControladorTaller::serviceConfirmation
  methods: GET

# Servicios de parking
aioParking:
  path: /aioParking
  controller: Sigae\Controllers\ControladorCliente::parking
  methods: GET

aioParkingBookSimple:
  path: /aioParkingBookSimple
  controller: Sigae\Controllers\ControladorCliente::parkingSimple
  methods: GET

aioParkingBookLongTerm:
  path: /aioParkingBookLongTerm
  controller: Sigae\Controllers\ControladorCliente::parkingLongTerm
  methods: GET

bookParkingSimple:
  path: /bookParkingSimple
  controller: Sigae\Controllers\ControladorParking::bookParkingSimple
  methods: POST

bookParkingLongTerm:
  path: /bookParkingLongTerm
  controller: Sigae\Controllers\ControladorParking::bookParkingLongTerm
  methods: POST

submitParking:
  path: /submitParking
  controller: Sigae\Controllers\ControladorParking::submitParking
  methods: POST

parkingConfirmation:
  path: /parkingConfirmation
  controller: Sigae\Controllers\ControladorParking::parkingConfirmation
  methods: GET

# Gestion de vehiculos
addVehicle:
  path: /addVehicle
  controller: Sigae\Controllers\ControladorVehiculo::addVehicle
  methods: POST

editVehicle:
  path: /editVehicle
  controller: Sigae\Controllers\ControladorVehiculo::editVehicle
  methods: POST

unlinkVehicle:
  path: /unlinkVehicle
  controller: Sigae\Controllers\ControladorVehiculo::unlinkVehicle
  methods: POST

# Rutas de cliente y gerente
products:
  path: /products
  controller: Sigae\Controllers\ControladorCliente::products
  methods: GET

filterProducts:
  path: /filterProducts
  controller: Sigae\Controllers\ControladorCliente::filterProducts
  methods: GET

# Rutas de funcionarios
# Gestion de Cuenta
loginAioEmployee:
  path: /loginAioEmployee
  controller: Sigae\Controllers\ControladorFuncionario::loginAioEmployee
  methods: GET

doLoginAioEmployee:
  path: /doLoginAioEmployee
  controller: Sigae\Controllers\ControladorFuncionario::doLoginAioEmployee
  methods: POST

# Home y apartados principales
showDashboard:
  path: /dashboard
  controller: Sigae\Controllers\ControladorFuncionario::showDashboard
  methods: GET

showReports:
  path: /reports
  controller: Sigae\Controllers\ControladorFuncionario::showReports
  methods: GET

stockManagement:
  path: /stockManagement
  controller: Sigae\Controllers\ControladorFuncionario::stockManagement
  methods: GET

inventory:
  path: /inventory
  controller: Sigae\Controllers\ControladorFuncionario::inventory
  methods: GET

prepareOrder:
  path: /prepareOrder
  controller: Sigae\Controllers\ControladorFuncionario::prepareOrder
  methods: GET

employeeManagement:
  path: /employeeManagement
  controller: Sigae\Controllers\ControladorFuncionario::employeeManagement
  methods: GET

# Gestion de funcionarios
# Consulta
showDiagnoseChiefs:
  path: /diagnoseChiefs
  controller: Sigae\Controllers\ControladorFuncionario::showDiagnoseChiefs
  methods: GET

showWorkshopChiefs:
  path: /workshopChiefs
  controller: Sigae\Controllers\ControladorFuncionario::showWorkshopChiefs
  methods: GET

showCashiers:
  path: /cashiers
  controller: Sigae\Controllers\ControladorFuncionario::showCashiers
  methods: GET

showValets:
  path: /valets
  controller: Sigae\Controllers\ControladorFuncionario::showValets
  methods: GET

showServiceExecutives:
  path: /serviceExecutives
  controller: Sigae\Controllers\ControladorFuncionario::showServiceExecutives
  methods: GET

# Alta
addDiagnoseChief:
  path: /addDiagnoseChief
  controller: Sigae\Controllers\ControladorFuncionario::addDiagnoseChief
  methods: POST

addWorkshopChief:
  path: /addWorkshopChief
  controller: Sigae\Controllers\ControladorFuncionario::addWorkshopChief
  methods: POST

addCashiers:
  path: /addCashier
  controller: Sigae\Controllers\ControladorFuncionario::addCashier
  methods: POST

addValet:
  path: /addValet
  controller: Sigae\Controllers\ControladorFuncionario::addValet
  methods: POST

addServiceExecutive:
  path: /addServiceExecutive
  controller: Sigae\Controllers\ControladorFuncionario::addServiceExecutive
  methods: POST

# Baja
deleteDiagnoseChief:
  path: /deleteDiagnoseChief
  controller: Sigae\Controllers\ControladorFuncionario::deleteDiagnoseChief
  methods: POST

deleteWorkshopChief:
  path: /deleteWorkshopChief
  controller: Sigae\Controllers\ControladorFuncionario::deleteWorkshopChief
  methods: POST

deleteCashiers:
  path: /deleteCashier
  controller: Sigae\Controllers\ControladorFuncionario::deleteCashier
  methods: POST

deleteValet:
  path: /deleteValet
  controller: Sigae\Controllers\ControladorFuncionario::deleteValet
  methods: POST

deleteServiceExecutive:
  path: /deleteServiceExecutive
  controller: Sigae\Controllers\ControladorFuncionario::deleteServiceExecutive
  methods: POST

# Modificacion
editDiagnoseChief:
  path: /editDiagnoseChief
  controller: Sigae\Controllers\ControladorFuncionario::editDiagnoseChief
  methods: POST

editWorkshopChief:
  path: /editWorkshopChief
  controller: Sigae\Controllers\ControladorFuncionario::editWorkshopChief
  methods: POST

editCashiers:
  path: /editCashier
  controller: Sigae\Controllers\ControladorFuncionario::editCashier
  methods: POST

editValet:
  path: /editValet
  controller: Sigae\Controllers\ControladorFuncionario::editValet
  methods: POST

editServiceExecutive:
  path: /editServiceExecutive
  controller: Sigae\Controllers\ControladorFuncionario::editServiceExecutive
  methods: POST

# Cambio clave
modPswdDiagnoseChief:
  path: /modPasswordDiagnoseChief
  controller: Sigae\Controllers\ControladorFuncionario::modPswdDiagnoseChief
  methods: POST

modPswdWorkshopChief:
  path: /modPasswordWorkshopChief
  controller: Sigae\Controllers\ControladorFuncionario::modPswdWorkshopChief
  methods: POST

modPswdCashiers:
  path: /modPasswordCashier
  controller: Sigae\Controllers\ControladorFuncionario::modPswdCashier
  methods: POST

modPswdValet:
  path: /modPasswordValet
  controller: Sigae\Controllers\ControladorFuncionario::modPswdValet
  methods: POST

modPswdServiceExecutive:
  path: /modPasswordServiceExecutive
  controller: Sigae\Controllers\ControladorFuncionario::modPswdServiceExecutive
  methods: POST

# Agenda de servicios de taller para ejecutivo
showServiceAgenda:
  path: /serviceAgenda
  controller: Sigae\Controllers\ControladorFuncionario::showServiceAgenda
  methods: GET

# Transacciones
createTransaction:
  path: /createTransaction
  controller: Sigae\Controllers\ControladorTransaccion::createTransaction
  methods: POST

# Registros de diagnosticos para jefe de diagnostico
showServiceDiagnosisRecords:
  path: /serviceDiagnosisRecords
  controller: Sigae\Controllers\ControladorFuncionario::showServiceDiagnosisRecords
  methods: GET

# Rutas de API
# Retornar datos de sesion de cliente 
getClientProfilePhoto:
  path: /api/getClientProfilePhoto
  controller: Sigae\Controllers\ControladorCliente::getClientProfilePhoto
  methods: GET

getClientEmail:
  path: /api/getClientEmail
  controller: Sigae\Controllers\ControladorCliente::getClientEmail
  methods: GET

getClientSession:
  path: /api/getClientSession
  controller: Sigae\Controllers\ControladorCliente::getClientSession
  methods: GET

getClientVehicles:
  path: /api/getClientVehicles
  controller: Sigae\Controllers\ControladorCliente::getClientVehicles
  methods: GET

# Retornar lapsos ocupados de taller en un dia 
getServicesSchedule:
  path: /api/getServicesSchedule
  controller: Sigae\Controllers\ControladorTaller::getServicesSchedule
  methods: GET