showLandingPage:
  path: /
  controller: Sigae\Controllers\ControladorCliente::showLandingPage
  methods: GET

login:
  path: /login
  controller: Sigae\Controllers\ControladorCliente::login
  methods: GET

logout:
  path: /logout
  controller: Sigae\Controllers\ControladorCliente::logout
  methods: POST

doLogin:
  path: /doLogin
  controller: Sigae\Controllers\ControladorCliente::doLogin
  methods: POST

doLoginOAuth:
  path: /doLoginOAuth
  controller: Sigae\Controllers\ControladorCliente::doLoginOAuth
  methods: GET

signup:
  path: /signup
  controller: Sigae\Controllers\ControladorCliente::signup
  methods: GET

doSignup:
  path: /doSignup
  controller: Sigae\Controllers\ControladorCliente::doSignup
  methods: POST

doSignupOAuth:
  path: /doSignupOAuth
  controller: Sigae\Controllers\ControladorCliente::doSignupOAuth
  methods: POST

forgotPassword:
  path: /forgotPassword
  controller: Sigae\Controllers\ControladorCliente::forgotPassword
  methods: GET

services:
  path: /services
  controller: Sigae\Controllers\ControladorCliente::services
  methods: GET

bookService:
  path: /bookService
  controller: Sigae\Controllers\ControladorCliente::bookService
  methods: GET

doBookService:
  path: /doBookService
  controller: Sigae\Controllers\ControladorTaller::doBookService
  methods: POST

uploadMyVehicles:
  path: /uploadMyVehicles
  controller: Sigae\Controllers\ControladorCliente::cargarMisVehiculosAjax

serviceConfirmation:
  path: /serviceConfirmation
  controller: Sigae\Controllers\ControladorTaller::serviceConfirmation
  methods: GET

aioParking:
  path: /aioParking
  controller: Sigae\Controllers\ControladorCliente::parking
  methods: GET

aioParkingBookSimple:
  path: /aioParkingBookSimple
  controller: Sigae\Controllers\ControladorCliente::parkingSimple
  methods: GET

aioParkingBookLongTerm:
  path: /aioParkingBookLongTerm
  controller: Sigae\Controllers\ControladorCliente::parkingLongTerm
  methods: GET

bookParkingSimple:
  path: /bookParkingSimple
  controller: Sigae\Controllers\ControladorParking::bookParkingSimple
  methods: POST

bookParkingLongTerm:
  path: /bookParkingLongTerm
  controller: Sigae\Controllers\ControladorParking::bookParkingLongTerm
  methods: POST

holdParkingSlot:
  path: /api/holdParkingSlot
  controller: Sigae\Controllers\ControladorParking::holdParkingSlot
  methods: POST

submitParkingSimple:
  path: /submitParkingSimple
  controller: Sigae\Controllers\ControladorParking::submitParkingSimple
  methods: POST

parkingConfirmation:
  path: /parkingConfirmation
  controller: Sigae\Controllers\ControladorParking::parkingConfirmation
  methods: GET

products:
  path: /products
  controller: Sigae\Controllers\ControladorCliente::products
  methods: GET

getClientProfilePhoto:
  path: /getClientProfilePhoto
  controller: Sigae\Controllers\ControladorCliente::getClientProfilePhoto
  methods: GET

getClientEmail:
  path: /getClientEmail
  controller: Sigae\Controllers\ControladorCliente::getClientEmail
  methods: GET

myAccount:
  path: /myAccount
  controller: Sigae\Controllers\ControladorCliente::myAccount
  methods: GET

editMyAccount:
  path: /editMyAccount
  controller: Sigae\Controllers\ControladorCliente::editMyAccount
  methods: POST

faq:
  path: /faq
  controller: Sigae\Controllers\ControladorCliente::faq
  methods: GET

home:
  path: /home
  controller: Sigae\Controllers\ControladorCliente::home
  methods: GET

loginAioEmployee:
  path: /loginAioEmployee
  controller: Sigae\Controllers\ControladorCliente::loginAioEmployee
  methods: GET

doLoginAioEmployee:
  path: /doLoginAioEmployee
  controller: Sigae\Controllers\ControladorCliente::doLoginAioEmployee
  methods: POST