<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXxrJVSv\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXxrJVSv/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXxrJVSv.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXxrJVSv\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXxrJVSv\App_KernelDevDebugContainer([
    'container.build_hash' => 'XxrJVSv',
    'container.build_id' => '858e64e4',
    'container.build_time' => 1728622817,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXxrJVSv');
